from ..tmdb import TMDBSeries, TMDBPerson

person = {
    "cast": [
        {
            "adult": False,
            "backdrop_path": None,
            "genre_ids": [18],
            "id": 207013,
            "original_language": "en",
            "original_title": "Henry",
            "overview": "Harassed single parent Karen lives with her two year old son Henry and gets no help from the child's father. Lack of childcare costs her a job interview and she goes to a park,leaving Henry with Anna,another mother whilst she goes for a drink. In the bar she picks up Martin and goes home with him for - unsatisfactory - sex but on returning to the park she finds Anna has called the police to whom she must give her address. This turns out to be a blessing in disguise when Martin follows her home and proves to be a potentially sympathetic friend.",
            "poster_path": "/lb0f1V3YRopm32FHhUw8s9TidIh.jpg",
            "release_date": "2013-06-30",
            "title": "Henry",
            "video": False,
            "vote_average": 8.0,
            "vote_count": 1,
            "popularity": 0.6,
            "character": "Karen",
            "credit_id": "52fe4d2dc3a368484e1db1b5",
            "order": 0,
            "media_type": "movie",
        },
        {
            "adult": False,
            "backdrop_path": None,
            "genre_ids": [35, 18],
            "id": 505319,
            "original_language": "en",
            "original_title": "Careful How You Go",
            "overview": "A darkly comic psychological horror, which visits three women as they indulge their taste for recreational cruelty.",
            "poster_path": "/3Bxj4wKMhQBL4hVHTIJwlVR3tv9.jpg",
            "release_date": "2018-01-19",
            "title": "Careful How You Go",
            "video": False,
            "vote_average": 0.0,
            "vote_count": 0,
            "popularity": 0.906,
            "character": "",
            "credit_id": "5a8565560e0a264011029694",
            "order": 1,
            "media_type": "movie",
        },
        {
            "adult": False,
            "backdrop_path": "/2g0pGowExWEq6G8ViBE8UDy1ZqN.jpg",
            "genre_ids": [18, 35],
            "id": 602346,
            "original_language": "en",
            "original_title": "The Reward",
            "overview": "Explores the moment of catharsis that unites two alienated New Yorkers over the disappearance of Mr. Puggles, the lost dog.",
            "poster_path": "/jah8ZlwucCTTM7LZFU81PI9SEkU.jpg",
            "release_date": "2010-04-10",
            "title": "The Reward",
            "video": False,
            "vote_average": 6.3,
            "vote_count": 4,
            "popularity": 0.6,
            "character": "Charlotte",
            "credit_id": "5cdadd050e0a2604afcea302",
            "order": 1,
            "media_type": "movie",
        },
        {
            "vote_average": 8.0,
            "overview": "Fleabag may seem oversexed, emotionally unfiltered and self-obsessed, but that's just the tip of the iceberg. With family and friendships under strain and a guinea pig café struggling to keep afloat, Fleabag suddenly finds herself with nothing to lose.",
            "id": 620350,
            "adult": False,
            "backdrop_path": "/avdCATeTca285BpMhLxSARIiFLG.jpg",
            "vote_count": 23,
            "genre_ids": [35],
            "release_date": "2019-09-12",
            "original_language": "en",
            "original_title": "National Theatre Live: Fleabag",
            "poster_path": "/wBmmX79NxG6LOztS3PI7uvc5ZBh.jpg",
            "title": "National Theatre Live: Fleabag",
            "video": True,
            "popularity": 4.532,
            "character": "Fleabag",
            "credit_id": "5d4565192d1e40349abedd6c",
            "order": 1,
            "media_type": "movie",
        },
        {
            "adult": False,
            "backdrop_path": None,
            "genre_ids": [35],
            "id": 325762,
            "original_language": "en",
            "original_title": "Meconium",
            "overview": "Owain's girlfriend Lorna has gone into labour unexpectedly. The baby is stuck in its sac and Owain's the only one who can do anything about it. Has he got what it takes when life gets messy?",
            "poster_path": "/jjuVFVtJ2BHMfo1OpLDzLm3HCb0.jpg",
            "release_date": "2011-10-24",
            "title": "Meconium",
            "video": False,
            "vote_average": 6.0,
            "vote_count": 1,
            "popularity": 0.6,
            "character": "Lorna",
            "credit_id": "5d8ff530109cd0002943bcca",
            "order": 1,
            "media_type": "movie",
        },
        {
            "adult": False,
            "backdrop_path": None,
            "genre_ids": [35, 16],
            "id": 637115,
            "original_language": "en",
            "original_title": "The 12 Days of Christmas: A Tale of Avian Misery",
            "overview": "A young woman receives all the gifts from the song The 12 Days Of Christmas from her boyfriend.",
            "poster_path": "/rI1qeoV45Bh3VqhWMhUUAXm1H7W.jpg",
            "release_date": "2016-01-01",
            "title": "The 12 Days of Christmas: A Tale of Avian Misery",
            "video": False,
            "vote_average": 8.0,
            "vote_count": 2,
            "popularity": 0.6,
            "character": "Narrator",
            "credit_id": "5d997eaa8c40f700197a8bb5",
            "order": 1,
            "media_type": "movie",
        },
        {
            "adult": False,
            "backdrop_path": None,
            "genre_ids": [99],
            "id": 825518,
            "original_language": "en",
            "original_title": "Love At First Swipe",
            "overview": "In an age of deadlines and bold headlines, how does anyone have the time to find love? The answer: speedy location-based mobile dating apps that cut to the chase of sexual attraction. In this bold new observational doc, we explore the world of online dating apps with jaw-dropping stories that capture the funny, heartwarming and often dangerous moments that make up the modern dating world.",
            "poster_path": "/gb5wK6JcjWBgBlXvb8U6SP4Z91L.jpg",
            "release_date": "2015-01-01",
            "title": "Love At First Swipe",
            "video": False,
            "vote_average": 0.0,
            "vote_count": 0,
            "popularity": 0.846,
            "character": "",
            "credit_id": "608fb06bdd83fa003f25548c",
            "order": 1,
            "media_type": "movie",
        },
        {
            "genre_ids": [28, 12],
            "id": 335977,
            "original_title": "Untitled Indiana Jones Project",
            "poster_path": "/pn0Wg5SgiEco44t3LSF9nH4fI4Y.jpg",
            "title": "Untitled Indiana Jones Project",
            "video": False,
            "vote_average": 0.0,
            "overview": 'The fifth and final entry in the "Indiana Jones" series.',
            "release_date": "2023-06-29",
            "vote_count": 0,
            "adult": False,
            "backdrop_path": "/AgoA1zXLXMHN6E9fDTYuE10Tmuc.jpg",
            "original_language": "en",
            "popularity": 16.07,
            "character": "",
            "credit_id": "60707c53924ce5003f3416e0",
            "order": 2,
            "media_type": "movie",
        },
        {
            "adult": False,
            "backdrop_path": None,
            "genre_ids": [35, 14, 12],
            "id": 639720,
            "original_language": "en",
            "original_title": "Imaginary Friends",
            "overview": "A man can see and talk to people's imaginary friends, befriending those that have been forgotten or discarded. However, some imaginary friends, lacking love and friendship, turn to the dark side and must be stopped.",
            "poster_path": None,
            "release_date": "2023-11-15",
            "title": "Imaginary Friends",
            "video": False,
            "vote_average": 0.0,
            "vote_count": 0,
            "popularity": 3.47,
            "character": "",
            "credit_id": "617b388eb458b8003056f277",
            "order": 2,
            "media_type": "movie",
        },
        {
            "adult": False,
            "backdrop_path": None,
            "genre_ids": [18, 27, 9648],
            "id": 637110,
            "original_language": "en",
            "original_title": "Beautiful Enough",
            "overview": "When a young girl, fixated on images of beautiful women, hears her parents go to bed she sets to work on her secret project.",
            "poster_path": "/iYNhFVtWebUuHVuOUMcjiTbxJW9.jpg",
            "release_date": "2011-01-11",
            "title": "Beautiful Enough",
            "video": False,
            "vote_average": 6.0,
            "vote_count": 1,
            "popularity": 0.876,
            "character": "(voice)",
            "credit_id": "5d997d368c40f700197a8a4c",
            "order": 3,
            "media_type": "movie",
        },
        {
            "adult": False,
            "backdrop_path": "/ghdK0Bt7o0CBqsihmUvZ09fGhJM.jpg",
            "genre_ids": [18, 53],
            "id": 925606,
            "original_language": "en",
            "original_title": "Intangible",
            "overview": "Billy believes his friends and family have been replaced by doubles. His psychiatrist believes this is a delusion. Meanwhile, Billy's carrying out an experiment to prove it's no delusion.",
            "poster_path": "/hzn11FlZgXrY2g8631qcG02gvJM.jpg",
            "release_date": "2008-07-22",
            "title": "Intangible",
            "video": False,
            "vote_average": 5.0,
            "vote_count": 1,
            "popularity": 0.6,
            "character": "Anna",
            "credit_id": "61dcb6b7ccb15f0042473cc8",
            "order": 3,
            "media_type": "movie",
        },
        {
            "id": 71688,
            "original_language": "en",
            "original_title": "The Iron Lady",
            "poster_path": "/nh1j03qFhbM3HdfGhB7aCxqLVQ.jpg",
            "video": False,
            "vote_average": 6.4,
            "vote_count": 1440,
            "overview": "A look at the life of Margaret Thatcher, the former Prime Minister of the United Kingdom, with a focus on the price she paid for power.",
            "release_date": "2011-12-26",
            "title": "The Iron Lady",
            "backdrop_path": "/oTDD5JFzJcuUEQC7sDyRyBigH9J.jpg",
            "adult": False,
            "genre_ids": [36, 18],
            "popularity": 11.863,
            "character": "Susie",
            "credit_id": "52fe4843c3a368484e0f0279",
            "order": 6,
            "media_type": "movie",
        },
        {
            "original_language": "en",
            "original_title": "Solo: A Star Wars Story",
            "poster_path": "/4oD6VEccFkorEBTEDXtpLAaz0Rl.jpg",
            "title": "Solo: A Star Wars Story",
            "video": False,
            "vote_average": 6.6,
            "overview": "Through a series of daring escapades deep within a dark and dangerous criminal underworld, Han Solo meets his mighty future copilot Chewbacca and encounters the notorious gambler Lando Calrissian.",
            "release_date": "2018-05-15",
            "vote_count": 7091,
            "adult": False,
            "backdrop_path": "/ojHCeDULAkQK25700fhRU75Tur2.jpg",
            "id": 348350,
            "genre_ids": [878, 12, 28],
            "popularity": 54.012,
            "character": "L3-37",
            "credit_id": "589ccef1925141088c001d7b",
            "order": 6,
            "media_type": "movie",
        },
        {
            "overview": "A 34 year old single woman, Nancy, hung-over again, exhausted by the endless fruitless set ups by her friends, traveling across London to toast another 10 years of her parent's successful happy magical marriage runs in with a 40 year old divorcee, Jack, who mistakes her for his 24 year old blind date. Nancy, deciding to go with it, happens to hop on the most chaotic yet hilarious journey of her life which neither of them will ever forget.",
            "release_date": "2015-05-29",
            "adult": False,
            "backdrop_path": "/mFjJeakcaiw7KZ4qWBsMStyZGXK.jpg",
            "genre_ids": [10749, 35],
            "vote_count": 804,
            "original_language": "en",
            "original_title": "Man Up",
            "id": 332340,
            "title": "Man Up",
            "video": False,
            "vote_average": 6.6,
            "poster_path": "/5tzWSEM6yNll5x0kQHuoeizPbGq.jpg",
            "popularity": 10.709,
            "character": "Katie",
            "credit_id": "572bd9d2c3a3687ffd000317",
            "order": 7,
            "media_type": "movie",
        },
        {
            "adult": False,
            "backdrop_path": "/tUVVEGe16K5hfN7jH5MhJYjbCt2.jpg",
            "genre_ids": [10751, 36, 18],
            "vote_count": 689,
            "original_language": "en",
            "original_title": "Goodbye Christopher Robin",
            "poster_path": "/a6IK3hMlUHzXZZVLBTh0WZ5KoAb.jpg",
            "vote_average": 7.1,
            "video": False,
            "id": 418680,
            "title": "Goodbye Christopher Robin",
            "overview": "The behind the scenes story of the life of A.A. Milne and the creation of the Winnie the Pooh stories inspired by his son Christopher Robin.",
            "release_date": "2017-09-29",
            "popularity": 11.488,
            "character": "Mary Brown",
            "credit_id": "58194e53c3a3680945002f8b",
            "order": 7,
            "media_type": "movie",
        },
        {
            "video": False,
            "vote_average": 8.0,
            "id": 645870,
            "overview": "Ten big name actors, including Jim Broadbent, Jodie Whittaker, David Tennant and Olivia Colman, come together to record an album for Children In Need",
            "release_date": "2019-10-30",
            "adult": False,
            "backdrop_path": None,
            "genre_ids": [99],
            "vote_count": 1,
            "original_language": "en",
            "original_title": "Children In Need 2019: Got It Covered",
            "poster_path": "/xKJdGcvo2gxA8lJVlSXJe6kgzH5.jpg",
            "title": "Children In Need 2019: Got It Covered",
            "popularity": 2.959,
            "character": "Self",
            "credit_id": "60b708646905fb006f611870",
            "order": 9,
            "media_type": "movie",
        },
        {
            "adult": False,
            "backdrop_path": "/oZbLtVbpNFmDa58woYqHBpHDxwt.jpg",
            "genre_ids": [18],
            "id": 73873,
            "original_language": "en",
            "original_title": "Albert Nobbs",
            "overview": "Albert Nobbs struggles to survive in late 19th century Ireland, where women aren't encouraged to be independent. Posing as a man, so she can work as a butler in Dublin's most posh hotel, Albert meets a handsome painter and looks to escape the lie she has been living.",
            "poster_path": "/68fdlvmqTWGC2y5nGXQE5RfgNB5.jpg",
            "release_date": "2011-12-21",
            "title": "Albert Nobbs",
            "video": False,
            "vote_average": 6.3,
            "vote_count": 377,
            "popularity": 8.337,
            "character": "Viscountess Yarrell",
            "credit_id": "5b09a8530e0a267c09006a8e",
            "order": 17,
            "media_type": "movie",
        },
        {
            "release_date": "2011-04-04",
            "adult": False,
            "backdrop_path": "/ggWV74vWCNjyBaa4dd8SBPMnxzp.jpg",
            "genre_ids": [18, 10752, 10770],
            "vote_count": 27,
            "original_language": "en",
            "original_title": "The Night Watch",
            "id": 70214,
            "title": "The Night Watch",
            "video": False,
            "vote_average": 5.5,
            "poster_path": "/7ayMrUTmt9FIqIOLrLZrlpWBFDX.jpg",
            "overview": "Set against the turbulent backdrop of London in the 1940s, this adaptation of Sarah Waters' bestselling novel, The Night Watch, follows four young Londoners inextricably linked by their wartime experiences. In a time when the barriers of sexual morality and social convention have been broken down, Kay, Helen, Viv and Duncan enjoy a freedom never experienced before.  Moving back in time through the 1940s into the maelstrom of the Blitz, the lives, loves and losses of these four central characters are unravelled. For them, the post-war victory is bittersweet, for it returns them to the margins of society, from which they hoped they had been liberated. In order to build their future they must each make peace with their past.",
            "popularity": 4.756,
            "character": "Lauren",
            "credit_id": "5d997bafb04605001a435d8e",
            "order": 23,
            "media_type": "movie",
        },
        {
            "original_language": "en",
            "id": 65251,
            "overview": "A comedy drama that crashes straight into the lives and loves of six twenty-something adults living together as Property Guardians in a disused hospital.",
            "vote_average": 7.3,
            "vote_count": 103,
            "original_name": "Crashing",
            "origin_country": ["GB"],
            "poster_path": "/7X09F4FWJa2OB62KVpYaFrX12ea.jpg",
            "first_air_date": "2016-01-11",
            "backdrop_path": "/5P6S91EXQMZJK5bHsm8RSQnkPMF.jpg",
            "genre_ids": [35],
            "name": "Crashing",
            "popularity": 10.402,
            "character": "Lulu",
            "credit_id": "56b015a19251410b3a0007d3",
            "episode_count": 6,
            "media_type": "tv",
        },
        {
            "backdrop_path": "/ddkbWeVyqvLyJa3QdNRalj8kMQJ.jpg",
            "first_air_date": "2016-07-21",
            "genre_ids": [35, 18],
            "id": 67070,
            "name": "Fleabag",
            "origin_country": ["GB"],
            "original_language": "en",
            "original_name": "Fleabag",
            "overview": "A comedy series adapted from the award-winning play about a young woman trying to cope with life in London whilst coming to terms with a recent tragedy.",
            "poster_path": "/27vEYsRKa3eAniwmoccOoluEXQ1.jpg",
            "vote_average": 8.2,
            "vote_count": 660,
            "popularity": 23.924,
            "character": "Fleabag",
            "credit_id": "5783be8ec3a36817390014a1",
            "episode_count": 12,
            "media_type": "tv",
        },
        {
            "backdrop_path": "/mtjJ8vsXmHuZVGqr6T0QnjzOqdz.jpg",
            "first_air_date": "2013-03-04",
            "genre_ids": [80, 18, 9648],
            "id": 1427,
            "name": "Broadchurch",
            "origin_country": ["GB"],
            "original_language": "en",
            "original_name": "Broadchurch",
            "overview": "The murder of a young boy in a small coastal town brings a media frenzy, which threatens to tear the community apart.",
            "poster_path": "/f5gQRyTZ3v4asugU2F5HXE2FIDg.jpg",
            "vote_average": 8.0,
            "vote_count": 551,
            "popularity": 24.718,
            "character": "Abby Thompson",
            "credit_id": "5894ab4cc3a36840a200811b",
            "episode_count": 8,
            "media_type": "tv",
        },
        {
            "genre_ids": [9648, 80, 18],
            "original_language": "en",
            "poster_path": "/nUNYOFd9SyFvlBbLg4Hym35LjeV.jpg",
            "vote_average": 6.1,
            "id": 61380,
            "overview": "In Overton, a remote little village in the English countryside, the townsfolk have two interests which are farming and racehorses. Life there seems simple but the village teens resort to playing chicken over razor-sharp blades spinning atop farm silos and other dangerous games to kill their boredom.\n\nThen, quite suddenly, life in Overton becomes a lot less boring. Another, much more literal type of killing is revealed when someone finds the body of a local teen under the wheels of a tractor. Now a murder investigation will bring to light all those secrets this close-knit community has been hiding, and life in Overton will never be the same.",
            "name": "Glue",
            "vote_count": 12,
            "original_name": "Glue",
            "origin_country": ["GB"],
            "backdrop_path": "/bKnBMAWr38XGGdO8scte1szAXh2.jpg",
            "first_air_date": "2014-09-15",
            "popularity": 6.989,
            "character": "Bee Warwick",
            "credit_id": "5a9599cf9251415639003554",
            "episode_count": 8,
            "media_type": "tv",
        },
        {
            "backdrop_path": "/2pJYis3LUEgFC3UErTQVgmUV1hN.jpg",
            "first_air_date": "2007-02-22",
            "genre_ids": [35, 10767],
            "id": 1220,
            "name": "The Graham Norton Show",
            "origin_country": ["GB"],
            "original_language": "en",
            "original_name": "The Graham Norton Show",
            "overview": "Each week celebrity guests join Irish comedian\xa0Graham Norton to discuss what's being going on around the world that week. The guests poke fun and share their opinions on the main news stories. Graham is often joined by a band or artist to play the show out.",
            "poster_path": "/vrbqaBXB8AALynQzpWz6JdCPEJS.jpg",
            "vote_average": 7.3,
            "vote_count": 186,
            "popularity": 89.306,
            "character": "Self",
            "credit_id": "5b02debc92514109a701933f",
            "episode_count": 2,
            "media_type": "tv",
        },
        {
            "backdrop_path": "/8rmFsSCjRJoE00ubC1f8CLu4HNz.jpg",
            "first_air_date": "2011-11-23",
            "genre_ids": [35],
            "id": 42178,
            "name": "The Café",
            "origin_country": [],
            "original_language": "en",
            "original_name": "The Café",
            "overview": "The Café is a British sitcom written by and starring Ralf Little and Michelle Terry broadcast by Sky1.",
            "poster_path": "/2LQ7tHgD78J9bPFoEbHjFKpB7Vn.jpg",
            "vote_average": 7.0,
            "vote_count": 2,
            "popularity": 2.882,
            "character": "Chloe Astill",
            "credit_id": "5b09a60ac3a3683a510056e3",
            "episode_count": 14,
            "media_type": "tv",
        },
        {
            "vote_average": 6.9,
            "original_name": "Saturday Night Live",
            "origin_country": ["US"],
            "id": 1667,
            "name": "Saturday Night Live",
            "backdrop_path": "/m5k30me2pdEUgXgb4R8AFIAObai.jpg",
            "genre_ids": [35, 10763],
            "original_language": "en",
            "vote_count": 306,
            "poster_path": "/bfiBW2qtdPEdcDOhYGNiP8XX8ok.jpg",
            "first_air_date": "1975-10-11",
            "overview": "A late-night live television sketch comedy and variety show created by Lorne Michaels. The show's comedy sketches, which parody contemporary culture and politics, are performed by a large and varying cast of repertory and newer cast members. Each episode is hosted by a celebrity guest, who usually delivers an opening monologue and performs in sketches with the cast, and features performances by a musical guest.",
            "popularity": 83.535,
            "character": "Self - Host",
            "credit_id": "5d81c331f6787a001e9d9715",
            "episode_count": 1,
            "media_type": "tv",
        },
        {
            "backdrop_path": "/gpDkx5Mog0jISp5rI7YbxQPKnCK.jpg",
            "first_air_date": "2015-08-02",
            "genre_ids": [10767],
            "id": 63498,
            "name": "Close Up with The Hollywood Reporter",
            "origin_country": ["US"],
            "original_language": "en",
            "original_name": "Close Up with The Hollywood Reporter",
            "overview": "Some of this year's most talked about talent open up about the challenges and triumphs of creating critically acclaimed series and performances.",
            "poster_path": "/vVRW8Mdfkq0pCtdeRIIXWQhbRUt.jpg",
            "vote_average": 6.0,
            "vote_count": 13,
            "popularity": 13.946,
            "character": "Self",
            "credit_id": "5e27a4b52dda89001256d334",
            "episode_count": 2,
            "media_type": "tv",
        },
        {
            "backdrop_path": "/gMMnf8VRg3Z98WaFmOLr9Jk8pIs.jpg",
            "first_air_date": "2015-09-08",
            "genre_ids": [35, 10767],
            "id": 63770,
            "name": "The Late Show with Stephen Colbert",
            "origin_country": ["US"],
            "original_language": "en",
            "original_name": "The Late Show with Stephen Colbert",
            "overview": 'Improv actor and comic Stephen Colbert leaves his "The Colbert Report" character behind as he makes his long-awaited return to television. As the host of The Late Show franchise redux - taped at the historic Ed Sullivan Theatre at New York - Colbert talks to actors, athletes, politicians, comics, artists and musicians as himself for the first time. Loyal fans, however, will also be treated to consistency as Colbert remains backed by many members of his writing and digital team from his former venture. Julliard-trained Jon Batiste serves as the bandleader.',
            "poster_path": "/9jkThAGYj2yp8jsS6Nriy5mzKFT.jpg",
            "vote_average": 6.5,
            "vote_count": 161,
            "popularity": 160.313,
            "character": "Herself",
            "credit_id": "5e9ef5d01f3319001f4c57fb",
            "episode_count": 1,
            "media_type": "tv",
        },
        {
            "genre_ids": [10765, 18],
            "original_language": "en",
            "original_name": "His Dark Materials",
            "origin_country": ["GB"],
            "name": "His Dark Materials",
            "vote_average": 8.0,
            "overview": "Lyra is an orphan who lives in a parallel universe in which science, theology and magic are entwined. Her search for a kidnapped friend uncovers a sinister plot involving stolen children, and turns into a quest to understand a mysterious phenomenon called Dust. She is later joined on her journey by Will, a boy who possesses a knife that can cut windows between worlds. As she learns the truth about her parents and her prophesied destiny, the two young people are caught up in a war against celestial powers that ranges across many worlds.",
            "id": 68507,
            "vote_count": 1085,
            "poster_path": "/g6tIKGc3f1H5QMz1dcgCwADKpZ7.jpg",
            "backdrop_path": "/9yKCJTOh9m3Lol2RY3kw99QPH6x.jpg",
            "first_air_date": "2019-11-03",
            "popularity": 61.975,
            "character": "Sayan Kotor (voice)",
            "credit_id": "5fd927e8511d0900415eb767",
            "episode_count": 2,
            "media_type": "tv",
        },
        {
            "original_language": "en",
            "name": "Staged",
            "first_air_date": "2020-06-10",
            "original_name": "Staged",
            "origin_country": ["GB"],
            "vote_average": 7.8,
            "id": 104674,
            "vote_count": 35,
            "poster_path": "/biZctcKYktjxP6CP2JzaJDoxs5p.jpg",
            "backdrop_path": "/kxbmn8lMOy7aVq7vV1e7cCGC60K.jpg",
            "overview": "David Tennant and Michael Sheen (playing themselves) were due to star in a production of 'Six Characters in Search of an Author' in the West End. The pandemic has put paid to that, but their director (Simon Evans) is determined not to let the opportunity pass him by.",
            "genre_ids": [35],
            "popularity": 8.321,
            "character": "Phoebe",
            "credit_id": "600ff5e392e55b003d699cf7",
            "episode_count": 1,
            "media_type": "tv",
        },
        {
            "id": 64591,
            "origin_country": ["GB"],
            "vote_average": 7.6,
            "overview": "London Irish follows the antics of four ex-pat Northern Irish 20 somethings in London. Written by Derry girl, Lisa McGee, someone who knows a thing or two about 'the craic' in world's best city. For these four friends it's not easy navigating their way through London life especially when they're playing by rules only they get which leads to a whole load of wrongdoings.",
            "vote_count": 7,
            "first_air_date": "2013-09-24",
            "backdrop_path": "/yVsEJ9Y4c50I5ZY5Fo7odcde2cd.jpg",
            "poster_path": "/wGpeMDbep7sn4m4OQbu3WQ1Bdwy.jpg",
            "genre_ids": [35],
            "name": "London Irish",
            "original_language": "en",
            "original_name": "London Irish",
            "popularity": 2.643,
            "character": "Steph",
            "credit_id": "6215e9180b5fd60069117146",
            "episode_count": 1,
            "media_type": "tv",
        },
    ],
    "crew": [
        {
            "vote_average": 8.0,
            "overview": "Fleabag may seem oversexed, emotionally unfiltered and self-obsessed, but that's just the tip of the iceberg. With family and friendships under strain and a guinea pig café struggling to keep afloat, Fleabag suddenly finds herself with nothing to lose.",
            "id": 620350,
            "adult": False,
            "backdrop_path": "/avdCATeTca285BpMhLxSARIiFLG.jpg",
            "vote_count": 23,
            "genre_ids": [35],
            "release_date": "2019-09-12",
            "original_language": "en",
            "original_title": "National Theatre Live: Fleabag",
            "poster_path": "/wBmmX79NxG6LOztS3PI7uvc5ZBh.jpg",
            "title": "National Theatre Live: Fleabag",
            "video": True,
            "popularity": 4.532,
            "credit_id": "5d4565332d1e40219bbdb1fb",
            "department": "Writing",
            "job": "Writer",
            "media_type": "movie",
        },
        {
            "adult": False,
            "backdrop_path": "/r2GAjd4rNOHJh6i6Y0FntmYuPQW.jpg",
            "genre_ids": [12, 28, 53],
            "vote_count": 4212,
            "original_language": "en",
            "original_title": "No Time to Die",
            "poster_path": "/iUgygt3fscRoKWCV1d0C7FbM9TP.jpg",
            "title": "No Time to Die",
            "video": False,
            "vote_average": 7.5,
            "id": 370172,
            "overview": "Bond has left active service and is enjoying a tranquil life in Jamaica. His peace is short-lived when his old friend Felix Leiter from the CIA turns up asking for help. The mission to rescue a kidnapped scientist turns out to be far more treacherous than expected, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.",
            "release_date": "2021-09-29",
            "popularity": 285.445,
            "credit_id": "5e56e686f48b34001577b646",
            "department": "Writing",
            "job": "Screenplay",
            "media_type": "movie",
        },
        {
            "backdrop_path": "/ddkbWeVyqvLyJa3QdNRalj8kMQJ.jpg",
            "first_air_date": "2016-07-21",
            "genre_ids": [35, 18],
            "id": 67070,
            "name": "Fleabag",
            "origin_country": ["GB"],
            "original_language": "en",
            "original_name": "Fleabag",
            "overview": "A comedy series adapted from the award-winning play about a young woman trying to cope with life in London whilst coming to terms with a recent tragedy.",
            "poster_path": "/27vEYsRKa3eAniwmoccOoluEXQ1.jpg",
            "vote_average": 8.2,
            "vote_count": 660,
            "popularity": 23.924,
            "credit_id": "5783be1c9251417df60022ae",
            "department": "Writing",
            "episode_count": 12,
            "job": "Writer",
            "media_type": "tv",
        },
        {
            "backdrop_path": "/2eR0H27Us1tvbjd95oW7WhiKioC.jpg",
            "first_air_date": "2018-04-08",
            "genre_ids": [80, 18],
            "id": 72750,
            "original_language": "en",
            "poster_path": "/4wKhTVw8aGq5AZMa0Q1spERdi7n.jpg",
            "vote_average": 8.1,
            "original_name": "Killing Eve",
            "origin_country": ["US"],
            "vote_count": 888,
            "overview": "A security consultant hunts for a ruthless assassin. Equally obsessed with each other, they go head to head in an epic game of cat-and-mouse.",
            "name": "Killing Eve",
            "popularity": 62.865,
            "credit_id": "5ac8cf730e0a2649710414f9",
            "department": "Writing",
            "episode_count": 8,
            "job": "Writer",
            "media_type": "tv",
        },
        {
            "original_language": "en",
            "id": 65251,
            "overview": "A comedy drama that crashes straight into the lives and loves of six twenty-something adults living together as Property Guardians in a disused hospital.",
            "vote_average": 7.3,
            "vote_count": 103,
            "original_name": "Crashing",
            "origin_country": ["GB"],
            "poster_path": "/7X09F4FWJa2OB62KVpYaFrX12ea.jpg",
            "first_air_date": "2016-01-11",
            "backdrop_path": "/5P6S91EXQMZJK5bHsm8RSQnkPMF.jpg",
            "genre_ids": [35],
            "name": "Crashing",
            "popularity": 10.402,
            "credit_id": "5b09d7bb9251414715007c32",
            "department": "Writing",
            "episode_count": 6,
            "job": "Writer",
            "media_type": "tv",
        },
        {
            "backdrop_path": "/ddkbWeVyqvLyJa3QdNRalj8kMQJ.jpg",
            "first_air_date": "2016-07-21",
            "genre_ids": [35, 18],
            "id": 67070,
            "name": "Fleabag",
            "origin_country": ["GB"],
            "original_language": "en",
            "original_name": "Fleabag",
            "overview": "A comedy series adapted from the award-winning play about a young woman trying to cope with life in London whilst coming to terms with a recent tragedy.",
            "poster_path": "/27vEYsRKa3eAniwmoccOoluEXQ1.jpg",
            "vote_average": 8.2,
            "vote_count": 660,
            "popularity": 23.924,
            "credit_id": "5b2e61bd9251416e00005249",
            "department": "Production",
            "episode_count": 6,
            "job": "Executive Producer",
            "media_type": "tv",
        },
        {
            "original_language": "en",
            "id": 65251,
            "overview": "A comedy drama that crashes straight into the lives and loves of six twenty-something adults living together as Property Guardians in a disused hospital.",
            "vote_average": 7.3,
            "vote_count": 103,
            "original_name": "Crashing",
            "origin_country": ["GB"],
            "poster_path": "/7X09F4FWJa2OB62KVpYaFrX12ea.jpg",
            "first_air_date": "2016-01-11",
            "backdrop_path": "/5P6S91EXQMZJK5bHsm8RSQnkPMF.jpg",
            "genre_ids": [35],
            "name": "Crashing",
            "popularity": 10.402,
            "credit_id": "5b2e61350e0a2657bf005fde",
            "department": "Production",
            "episode_count": 6,
            "job": "Associate Producer",
            "media_type": "tv",
        },
        {
            "backdrop_path": "/2eR0H27Us1tvbjd95oW7WhiKioC.jpg",
            "first_air_date": "2018-04-08",
            "genre_ids": [80, 18],
            "id": 72750,
            "original_language": "en",
            "poster_path": "/4wKhTVw8aGq5AZMa0Q1spERdi7n.jpg",
            "vote_average": 8.1,
            "original_name": "Killing Eve",
            "origin_country": ["US"],
            "vote_count": 888,
            "overview": "A security consultant hunts for a ruthless assassin. Equally obsessed with each other, they go head to head in an epic game of cat-and-mouse.",
            "name": "Killing Eve",
            "popularity": 62.865,
            "credit_id": "5b723c080e0a267ef41a61e4",
            "department": "Production",
            "episode_count": 16,
            "job": "Executive Producer",
            "media_type": "tv",
        },
        {
            "original_language": "en",
            "poster_path": "/rbYfDspa6vUTAxif5SZJABgB8pr.jpg",
            "id": 87393,
            "first_air_date": "2020-04-12",
            "name": "RUN",
            "vote_count": 138,
            "vote_average": 6.8,
            "overview": "Ruby is living a humdrum existence when one day she gets a text inviting her to fulfill a youthful pact, promising true love and self-reinvention, by stepping out of her life to take a journey with her oldest flame.",
            "backdrop_path": "/7aMoV1v6A8uwTRaGV8LHIBcVBuN.jpg",
            "original_name": "RUN",
            "origin_country": ["US"],
            "genre_ids": [35, 18],
            "popularity": 9.495,
            "credit_id": "5c80550a0e0a2643035d2944",
            "department": "Production",
            "episode_count": 7,
            "job": "Executive Producer",
            "media_type": "tv",
        },
        {
            "backdrop_path": "/2eR0H27Us1tvbjd95oW7WhiKioC.jpg",
            "first_air_date": "2018-04-08",
            "genre_ids": [80, 18],
            "id": 72750,
            "original_language": "en",
            "poster_path": "/4wKhTVw8aGq5AZMa0Q1spERdi7n.jpg",
            "vote_average": 8.1,
            "original_name": "Killing Eve",
            "origin_country": ["US"],
            "vote_count": 888,
            "overview": "A security consultant hunts for a ruthless assassin. Equally obsessed with each other, they go head to head in an epic game of cat-and-mouse.",
            "name": "Killing Eve",
            "popularity": 62.865,
            "credit_id": "623961d1d29bdd00786ca6cf",
            "department": "Crew",
            "episode_count": 32,
            "job": "Creator",
            "media_type": "tv",
        },
        {
            "backdrop_path": "/ddkbWeVyqvLyJa3QdNRalj8kMQJ.jpg",
            "first_air_date": "2016-07-21",
            "genre_ids": [35, 18],
            "id": 67070,
            "name": "Fleabag",
            "origin_country": ["GB"],
            "original_language": "en",
            "original_name": "Fleabag",
            "overview": "A comedy series adapted from the award-winning play about a young woman trying to cope with life in London whilst coming to terms with a recent tragedy.",
            "poster_path": "/27vEYsRKa3eAniwmoccOoluEXQ1.jpg",
            "vote_average": 8.2,
            "vote_count": 660,
            "popularity": 23.924,
            "credit_id": "5783be01c3a368424c00249b",
            "department": "Creator",
            "job": "Creator",
            "media_type": "tv",
        },
        {
            "original_language": "en",
            "id": 65251,
            "overview": "A comedy drama that crashes straight into the lives and loves of six twenty-something adults living together as Property Guardians in a disused hospital.",
            "vote_average": 7.3,
            "vote_count": 103,
            "original_name": "Crashing",
            "origin_country": ["GB"],
            "poster_path": "/7X09F4FWJa2OB62KVpYaFrX12ea.jpg",
            "first_air_date": "2016-01-11",
            "backdrop_path": "/5P6S91EXQMZJK5bHsm8RSQnkPMF.jpg",
            "genre_ids": [35],
            "name": "Crashing",
            "popularity": 10.402,
            "credit_id": "5b09d82e0e0a267c27007e5e",
            "department": "Creator",
            "job": "Creator",
            "media_type": "tv",
        },
        {
            "poster_path": None,
            "vote_average": 0.0,
            "overview": "Based on the 2005 film Mr. & Mrs. Smith.",
            "origin_country": ["US"],
            "id": 118642,
            "name": "Mr. & Mrs. Smith",
            "backdrop_path": None,
            "vote_count": 0,
            "genre_ids": [],
            "original_name": "Mr. & Mrs. Smith",
            "original_language": "en",
            "popularity": 1.4,
            "credit_id": "602734a2df857c003fde9e65",
            "department": "Creator",
            "job": "Creator",
            "media_type": "tv",
        },
    ],
    "id": 1023483,
}
series = {
    "adult": False,
    "backdrop_path": "/t15KHp3iNfHVQBNIaqUGW12xQA4.jpg",
    "created_by": [
        {
            "id": 24951,
            "credit_id": "52599cb3760ee34661b60d9a",
            "name": "Peter Gould",
            "gender": 2,
            "profile_path": "/il6NSy05UnO7SV9SgzEqKHXioNl.jpg",
        },
        {
            "id": 66633,
            "credit_id": "52599cb3760ee34661b60d94",
            "name": "Vince Gilligan",
            "gender": 2,
            "profile_path": "/uFh3OrBvkwKSU3N5y0XnXOhqBJz.jpg",
        },
    ],
    "episode_run_time": [45],
    "first_air_date": "2015-02-08",
    "genres": [{"id": 80, "name": "Crime"}, {"id": 18, "name": "Drama"}],
    "homepage": "https://www.amc.com/shows/better-call-saul--1002228",
    "id": 60059,
    "in_production": True,
    "languages": ["en"],
    "last_air_date": "2022-05-23",
    "last_episode_to_air": {
        "air_date": "2022-05-23",
        "episode_number": 7,
        "id": 3641946,
        "name": "Plan and Execution",
        "overview": "Jimmy and Kim deal with a last-minute snag. Howard's investigation finally yields results.",
        "production_code": "",
        "runtime": 50,
        "season_number": 6,
        "still_path": "/flVUI98wSTtLmYDCx81gowleQTe.jpg",
        "vote_average": 10.0,
        "vote_count": 5,
    },
    "name": "Better Call Saul",
    "next_episode_to_air": {
        "air_date": "2022-07-11",
        "episode_number": 8,
        "id": 3641948,
        "name": "",
        "overview": "",
        "production_code": "",
        "runtime": None,
        "season_number": 6,
        "still_path": None,
        "vote_average": 0.0,
        "vote_count": 0,
    },
    "networks": [
        {
            "name": "AMC",
            "id": 174,
            "logo_path": "/pmvRmATOCaDykE6JrVoeYxlFHw3.png",
            "origin_country": "US",
        }
    ],
    "number_of_episodes": 63,
    "number_of_seasons": 6,
    "origin_country": ["US"],
    "original_language": "en",
    "original_name": "Better Call Saul",
    "overview": 'Six years before Saul Goodman meets Walter White. We meet him when the man who will become Saul Goodman is known as Jimmy McGill, a small-time lawyer searching for his destiny, and, more immediately, hustling to make ends meet. Working alongside, and, often, against Jimmy, is “fixer” Mike Ehrmantraut. The series tracks Jimmy’s transformation into Saul Goodman, the man who puts “criminal” in “criminal lawyer".',
    "popularity": 237.057,
    "poster_path": "/fC2HDm5t0kHl7mTm7jxMR31b7by.jpg",
    "production_companies": [
        {
            "id": 11073,
            "logo_path": "/wHs44fktdoj6c378ZbSWfzKsM2Z.png",
            "name": "Sony Pictures Television Studios",
            "origin_country": "US",
        },
        {
            "id": 23242,
            "logo_path": "/fOALFvgnO1ZdIaA9PNIAAuaDKWd.png",
            "name": "AMC Networks",
            "origin_country": "US",
        },
    ],
    "production_countries": [
        {"iso_3166_1": "US", "name": "United States of America"}
    ],
    "seasons": [
        {
            "air_date": "2014-12-17",
            "episode_count": 5,
            "id": 64929,
            "name": "Specials",
            "overview": "",
            "poster_path": "/oaF4Fj0FafTEK2CX9aiIW42oABe.jpg",
            "season_number": 0,
        },
        {
            "air_date": "2015-02-08",
            "episode_count": 10,
            "id": 60223,
            "name": "Season 1",
            "overview": "When we meet him, the man who will become Saul Goodman is known as Jimmy McGill, a small-time lawyer searching for his destiny, and, more immediately, hustling to make ends meet. Working alongside, and often against, Jimmy is “fixer” Mike Erhmantraut.",
            "poster_path": "/iwwHYFrVJF3mkHHMp77120gnYUq.jpg",
            "season_number": 1,
        },
        {
            "air_date": "2016-02-15",
            "episode_count": 10,
            "id": 72040,
            "name": "Season 2",
            "overview": "Season one left Jimmy at the center of a large class-action lawsuit that led to a promising job opportunity at a prestigious firm in Santa Fe. Having arrived at a fork in the road, will Jimmy take the straight and narrow path with a safe corporate job or will he fall back into his “Slippin’ Jimmy” con artist ways?",
            "poster_path": "/7othdOzr1RFJaIUuyhNlbWPLiA7.jpg",
            "season_number": 2,
        },
        {
            "air_date": "2017-04-10",
            "episode_count": 10,
            "id": 83956,
            "name": "Season 3",
            "overview": "As the season three begins, the repercussions of Chuck's scheme test Jimmy and Kim's fledgling law practices -- and their romance -- as never before. This imminent existential threat presses Jimmy’s faltering moral compass to the limit. Meanwhile, Mike searches for a mysterious adversary who seems to know almost everything about his business.",
            "poster_path": "/tVxi5KuJJAmAuDdSyZUPiURDPcV.jpg",
            "season_number": 3,
        },
        {
            "air_date": "2018-08-06",
            "episode_count": 10,
            "id": 104603,
            "name": "Season 4",
            "overview": "In Season 4, in the wake of a loss, Jimmy takes steps into the criminal world that will put his future as a lawyer — and his relationship with Kim — in jeopardy.",
            "poster_path": "/56YsRH5U0Yx0hklQX0V7aXNjRDn.jpg",
            "season_number": 4,
        },
        {
            "air_date": "2020-02-23",
            "episode_count": 10,
            "id": 136162,
            "name": "Season 5",
            "overview": "Jimmy finally makes the decision that changes everything — to practice law as “Saul Goodman.” And this decision will soon create unexpected and profound waves of change for everyone in his world.",
            "poster_path": "/mAgBQaGqoDUgCAmntKiqp61y1Ec.jpg",
            "season_number": 5,
        },
        {
            "air_date": "2022-04-18",
            "episode_count": 13,
            "id": 243392,
            "name": "Season 6",
            "overview": "The final season concludes the complicated journey and transformation of its compromised hero, Jimmy McGill, into criminal lawyer Saul Goodman. From the cartel to the courthouse, from Albuquerque to Omaha, season six tracks Jimmy, Saul and Gene as well as Jimmy’s complex relationship with Kim, who is in the midst of her own existential crisis. Meanwhile, Mike, Gus, Nacho and Lalo are locked into a game of cat and mouse with mortal stakes.",
            "poster_path": "/rbNc44otT6VRd7QpxqlUAMyByaQ.jpg",
            "season_number": 6,
        },
    ],
    "spoken_languages": [
        {"english_name": "English", "iso_639_1": "en", "name": "English"}
    ],
    "status": "Returning Series",
    "tagline": "Putting the “criminal” in “criminal lawyer.”",
    "type": "Scripted",
    "vote_average": 8.5,
    "vote_count": 2823,
}


def test_tmdb_person_parser():
    parser = TMDBPerson()
    result = [x for x in parser.parse_releases(person)]
    assert len(result) == 42
    sample = result[0]
    assert sample["title"] == "Henry"


def test_tmdb_series_parser():
    parser = TMDBSeries()
    result = [x for x in parser.parse_releases(series)]
    assert len(result) == 1
    assert result[0]["title"] == "Plan and Execution"
