version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: busride
    image: busride
    env_file: .env
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    ports:
      - 80:80
