version: "3"

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: busride-worker
    image: busride-worker
    env_file: .env
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
