"""empty message

Revision ID: b97c4ef2231f
Revises: d3bc0769ac18
Create Date: 2022-01-28 15:45:02.283402

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b97c4ef2231f'
down_revision = 'd3bc0769ac18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases', sa.Column('title', sa.String(length=255), nullable=False))
    op.create_index('release_idx_entity_title', 'releases', ['title', 'entity_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('release_idx_entity_title', table_name='releases')
    op.drop_column('releases', 'title')
    # ### end Alembic commands ###
