"""empty message

Revision ID: d3bc0769ac18
Revises: 6f94ced7a24f
Create Date: 2022-01-23 12:18:42.843558

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "d3bc0769ac18"
down_revision = "6f94ced7a24f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_releases_release_date"),
        "releases",
        ["release_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_releases_release_date"), table_name="releases")
    # ### end Alembic commands ###
