"""empty message

Revision ID: e0b53aec1ab5
Revises: b97c4ef2231f
Create Date: 2022-01-28 15:55:31.289627

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'e0b53aec1ab5'
down_revision = 'b97c4ef2231f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('apis_user_id_fkey', 'apis', type_='foreignkey')
    op.create_foreign_key(None, 'apis', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('interests_user_id_fkey', 'interests', type_='foreignkey')
    op.create_foreign_key(None, 'interests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('releases_entity_id_fkey', 'releases', type_='foreignkey')
    op.create_foreign_key(None, 'releases', 'entities', ['entity_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'releases', type_='foreignkey')
    op.create_foreign_key('releases_entity_id_fkey', 'releases', 'entities', ['entity_id'], ['id'])
    op.drop_constraint(None, 'interests', type_='foreignkey')
    op.create_foreign_key('interests_user_id_fkey', 'interests', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'apis', type_='foreignkey')
    op.create_foreign_key('apis_user_id_fkey', 'apis', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
