# global:
#   imageRegistry:

image:
  registry: docker.io
  repository: bitnami/mongodb
  tag: 4.0.6

  pullPolicy: Always
  # pullSecrets:
  #   - myRegistrKeySecretName

  debug: false

#
usePassword: false

# mongodbUsername: username
# mongodbPassword: password
# mongodbDatabase: database

mongodbEnableIPv6: false

mongodbSystemLogVerbosity: 0
mongodbDisableSystemLog: false

mongodbExtraFlags: []

securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001

clusterDomain: cluster.local

service:
  annotations: {}
  type: ClusterIP
  # clusterIP: None
  port: 27017

  # nodePort:


#
replicaSet:
  enabled: false
  useHostnames: true

  name: rs0

  # key: key

  replicas:
    secondary: 1
    arbiter: 1
  pdb:
    minAvailable:
      primary: 1
      secondary: 1
      arbiter: 1

# Annotations to be added to MongoDB pods
podAnnotations: {}

# Additional pod labels to apply
podLabels: {}

resources: {}
# limits:
#   cpu: 500m
#   memory: 512Mi
# requests:
#   cpu: 100m
#   memory: 256Mi

nodeSelector: {}

affinity: {}

tolerations: []

persistence:
  enabled: true
  # existingClaim:

  storageClass: local
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  annotations: {}

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

# Entries for the MongoDB config file
configmap:
#  # Where and how to store data.
#  storage:
#    dbPath: /opt/bitnami/mongodb/data/db
#    journal:
#      enabled: true
#    #engine:
#    #wiredTiger:
#  # where to write logging data.
#  systemLog:
#    destination: file
#    logAppend: true
#    path: /opt/bitnami/mongodb/logs/mongodb.log
#  # network interfaces
#  net:
#    port: 27017
#    bindIp: 0.0.0.0
#    unixDomainSocket:
#      enabled: true
#      pathPrefix: /opt/bitnami/mongodb/tmp
#  # replica set options
#  replication:
#    replSetName: replicaset
#  # process management options
#  processManagement:
#     fork: false
#     pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
#  # set parameter options
#  setParameter:
#     enableLocalhostAuthBypass: true
#  # security options
#  security:
#    authorization: enabled
#    keyFile: /opt/bitnami/mongodb/conf/keyfile

metrics:
  enabled: false

  image:
    registry: docker.io
    repository: forekshub/percona-mongodb-exporter
    tag: latest
    pullPolicy: IfNotPresent
    # pullSecrets:
    #   - myRegistrKeySecretName

  # resources: {}

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9216"

  serviceMonitor:
    enabled: false
    additionalLabels: {}

    # relabellings:

    alerting:
      rules: {}

      additionalLabels: {}
